.TH "main.cpp" 3 "Pytanie czy Wyzwanie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- Plik Ÿród³owy g³ównego programu\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Quest\&.h'\fP
.br
\fC#include 'Quest\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Plik Ÿród³owy g³ównego programu\&. 


.SH "Function Documentation"
.PP 
.SS "int main ()"
G³ówna funkcja programu\&.
.PP
Tworzy obiekt klasy \fC\fBQuest\fP\fP, wywo³uje funkcje \fCConsole()\fP, \fCWelcome()\fP, i \fCMenu()\fP, a nastêpnie zwraca 0\&.
.PP
\fBReturns\fP
.RS 4
0 po zakoñczeniu programu\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pytanie czy Wyzwanie from the source code\&.
