.TH "Quest.h" 3 "Pytanie czy Wyzwanie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quest.h \- Plik nag³ówkowy klasy \fBQuest\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQuest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Plik nag³ówkowy klasy \fBQuest\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Pytanie czy Wyzwanie from the source code\&.
